server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Optimización de conexiones para procesos por lotes en microservicios
    proxy_connect_timeout       90s;
    proxy_send_timeout          90s;
    proxy_read_timeout          90s;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    # Configuración base reutilizable para Headers de Proxy
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    add_header Cache-Control "no-store";

    # API proxy — Auth Service
    location /api/auth/ {
        proxy_pass http://worldcup-auth-service:3001;
        proxy_http_version 1.1;
    }

    location /api/admin/users {
        proxy_pass http://worldcup-auth-service:3001;
        proxy_http_version 1.1;
    }

    location /api/admin/invite-codes {
        proxy_pass http://worldcup-auth-service:3001;
        proxy_http_version 1.1;
    }

    # API proxy — Matches Service
    location /api/matches {
        proxy_pass http://worldcup-matches-service:3002;
        proxy_http_version 1.1;
    }

    location /api/admin/matches {
        proxy_pass http://worldcup-matches-service:3002;
        proxy_http_version 1.1;
    }

    # API proxy — Predictions & Leaderboard Service
    location /api/admin/leaderboard {
        proxy_pass http://worldcup-predictions-service:3003;
        proxy_http_version 1.1;
    }

    location /api/admin/bonus {
        proxy_pass http://worldcup-predictions-service:3003;
        proxy_http_version 1.1;
    }

    location /api/bonus {
        proxy_pass http://worldcup-predictions-service:3003;
        proxy_http_version 1.1;
    }

    location /api/predictions {
        proxy_pass http://worldcup-predictions-service:3003;
        proxy_http_version 1.1;
    }

    location /api/leaderboard {
        proxy_pass http://worldcup-predictions-service:3003;
        proxy_http_version 1.1;
    }

    # SPA fallback — redirecciona las rutas de React al index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Caché agresivo para optimizar el consumo de la t2.micro en AWS
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
